apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blackbox
  name: blackbox
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      targetPort: 9115
  selector:
    io.kompose.service: blackbox
