apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm0
  labels:
    io.kompose.service: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      scrape_timeout: 3s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    rule_files: []

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: blackbox-http
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - http://{{ .Values.FLASK_DEV_TARGET }}
              - http://{{ .Values.FLASK_PROD_TARGET }}
              - https://student.psu.ru
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox:9115

      - job_name: view_total
        metrics_path: /metrics
        scrape_interval: 15s
        scrape_timeout: 10s
        static_configs:
          - targets:
              - {{ .Values.FLASK_DEV_TARGET | quote }}
              - {{ .Values.FLASK_PROD_TARGET | quote }}
            labels:
              service: 'Flask-Redis-App'
